### ISSUE TITLE
 `h2o_context(sc)` returns error in spark  Cluster standalone

### ISSUE THREAD

**Issue by BruceZhaoR** [h2oai/rsparkling#32]
```r
> sc
$master
[1] "spark://hadooptest:7078"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$sparklyr.cores.local
[1] 8

$config$spark.sql.shuffle.partitions.local
[1] 8

$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.csv.embedded
[1] "^1.*"

$config$`sparklyr.shell.driver-class-path`
[1] ""

attr(,"config")
[1] "default"
attr(,"file")
[1] "/home/R/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/conf/config-template.yml"

$spark_home
[1] "/data/R/epel/spark-2.1.0-bin-hadoop2.6"

$backend
        description               class                mode                text              opened            can read 
"->localhost:53014"          "sockconn"                "wb"            "binary"            "opened"               "yes" 
          can write 
              "yes" 

$monitor
        description               class                mode                text              opened            can read 
"->localhost:52473"          "sockconn"                "rb"            "binary"            "opened"               "yes" 
          can write 
              "yes" 

$output_file
[1] "/tmp/RtmpRSg8PE/file255a6460772d_spark.log"

$spark_context
<jobj[4]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@35674ece

$java_context
<jobj[5]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@627538f8

$hive_context
<jobj[8]>
  class org.apache.spark.sql.SparkSession
  org.apache.spark.sql.SparkSession@3f115a45

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection"  

# Erros
> h2o_context(sc)
Errors: java.lang.ClassNotFoundException: org.apache.spark.h2o.H2OContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:77)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

> Sys.getenv("SPARK_HOME")
[1] "/data/R/epel/spark-2.1.0-bin-hadoop2.6"
> getOption("rsparkling.sparklingwater.version")
[1] "2.1.0"
> getOption("rsparkling.sparklingwater.location")
[1] "/data/R/epel/sparkling-water-2.1.0/assembly/build/libs/sparkling-water-assembly_2.11-2.1.0-all.jar"

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C               LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8    LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsparkling_0.2.0 h2o_3.10.3.2     dplyr_0.5.0      sparklyr_0.5.4  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     withr_1.0.2      digest_0.6.12    rprojroot_1.2    assertthat_0.2.0 bitops_1.0-6     rappdirs_0.3.1  
 [8] R6_2.2.1         jsonlite_1.4     DBI_0.6-1        backports_1.0.5  magrittr_1.5     httr_1.2.1       rlang_0.1.1     
[15] lazyeval_0.2.0   config_0.2       tools_3.3.3      readr_1.1.1      RCurl_1.95-4.8   hms_0.3          parallel_3.3.3  
[22] yaml_2.1.14      base64enc_0.1-3  tibble_1.3.1 
```

Please help me with this problem, thank you in advanced !   Feel free to ask me for more information. ^_^

**Comment by BruceZhaoR** [comment]
Solved!   Sorry,my fault. I forget to start sparkling water   `nohup sparkling-shell > ./test.out &`
